In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [3]:
exo = pd.read_csv('exoplanet_cleaned.csv')
exo

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0          CONFIRMED              0              0              0   
1          CONFIRMED              0              0              0   
2     FALSE POSITIVE              0              1              0   
3     FALSE POSITIVE              0              1              0   
4          CONFIRMED              0              0              0   
...              ...            ...            ...            ...   
6625  FALSE POSITIVE              0              1              0   
6626  FALSE POSITIVE              0              0              0   
6627  FALSE POSITIVE              0              1              1   
6628  FALSE POSITIVE              0              0              1   
6629  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0    9.488036     2.775000e-05    -2.775000e-05   
1                 0   54.418383     2.479000e-04    -2.479000e-04   
2                 0   19.899140     1.494000e-05    -1.494000e-05   
3                 0    1.736952     2.630000e-07    -2.630000e-07   
4                 0    2.525592     3.761000e-06    -3.761000e-06   
...             ...         ...              ...              ...   
6625              0   23.627035     2.264000e-04    -2.264000e-04   
6626              1    8.589871     1.846000e-04    -1.846000e-04   
6627              0    0.527699     1.160000e-07    -1.160000e-07   
6628              0    0.681402     2.434000e-06    -2.434000e-06   
6629              1    4.856035     6.356000e-05    -6.356000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      170.538750          0.002160  ...           -81.0      4.467   
1      162.513840          0.003520  ...           -81.0      4.467   
2      175.850252          0.000581  ...          -176.0      4.544   
3      170.307565          0.000115  ...          -174.0      4.564   
4      171.595550          0.001130  ...          -211.0      4.438   
...           ...               ...  ...             ...        ...   
6625   150.036200          0.010900  ...          -185.0      4.477   
6626   132.016100          0.015700  ...          -152.0      4.296   
6627   131.705093          0.000170  ...          -166.0      4.529   
6628   132.181750          0.002850  ...          -236.0      4.447   
6629   135.993300          0.010800  ...          -225.0      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.064          -0.096     0.927          0.105         -0.061   
2              0.044          -0.176     0.868          0.233         -0.078   
3              0.053          -0.168     0.791          0.201         -0.067   
4              0.070          -0.210     1.046          0.334         -0.133   
...              ...             ...       ...            ...            ...   
6625           0.099          -0.121     0.857          0.138         -0.101   
6626           0.231          -0.189     1.088          0.313         -0.228   
6627           0.035          -0.196     0.903          0.237         -0.079   
6628           0.056          -0.224     1.041          0.341         -0.114   
6629           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     291.93423  48.141651      15.347  
2     297.00482  48.134129      15.436  
3     285.53461  48.285210      15.597  
4     288.75488  48.226200      15.509  
...         ...        ...         ...  
6625  299.21881  44.181862      16.375  
6626  298.74921  46.973351      14.478  
6627  297.18875  47.093819      14.082  
6628  294.16489  47.176281      15.385  
6629  297.00977  47.121021      14.826  

[6630 rows x 41 columns]

In [4]:
#X and y values
#drop y vales and string object from df
X = exo.drop(columns=['koi_disposition']).values
y = exo["koi_disposition"].values

print(X.shape, y.shape)
X

(6630, 40) (6630,)


array([[  0.      ,   0.      ,   0.      , ..., 291.93423 ,  48.141651,
         15.347   ],
       [  0.      ,   0.      ,   0.      , ..., 291.93423 ,  48.141651,
         15.347   ],
       [  0.      ,   1.      ,   0.      , ..., 297.00482 ,  48.134129,
         15.436   ],
       ...,
       [  0.      ,   1.      ,   1.      , ..., 297.18875 ,  47.093819,
         14.082   ],
       [  0.      ,   0.      ,   1.      , ..., 294.16489 ,  47.176281,
         15.385   ],
       [  0.      ,   0.      ,   1.      , ..., 297.00977 ,  47.121021,
         14.826   ]])

In [5]:
#separate 'training' and 'testing' data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [6]:
type(y_train)

numpy.ndarray

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=500)#default=100 did not work
classifier

LogisticRegression(max_iter=500)

In [8]:
from sklearn.preprocessing import MinMaxScaler
X_scale = MinMaxScaler().fit(X_train)

X_train_scaled = X_scale.transform(X_train)
X_test_scaled = X_scale.transform(X_test)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y = label_encoder.transform(y_train)
y_train, encoded_y

(array(['CONFIRMED', 'CONFIRMED', 'CONFIRMED', ..., 'FALSE POSITIVE',
        'CONFIRMED', 'FALSE POSITIVE'], dtype=object),
 array([0, 0, 0, ..., 1, 0, 1]))

In [9]:
from sklearn.model_selection import GridSearchCV
import numpy as np
#penalty = ['l1', 'none']

params = {'penalty': ['l2', 'none']}
C = np.logspace(0,1)

grid = GridSearchCV(classifier, dict(C=C),cv=5, verbose=3)
grid

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=500),
             param_grid={'C': array([ 1.        ,  1.04811313,  1.09854114,  1.1513954 ,  1.20679264,
        1.26485522,  1.32571137,  1.38949549,  1.45634848,  1.52641797,
        1.59985872,  1.67683294,  1.75751062,  1.84206997,  1.93069773,
        2.02358965,  2.12095089,  2.22299648,  2.32995181,  2.44205309,
        2.55954792,  2.6826958 ,  2.8117687 ,  2.9470517 ,  3.0888436 ,
        3.23745754,  3.39322177,  3.55648031,  3.72759372,  3.90693994,
        4.09491506,  4.29193426,  4.49843267,  4.71486636,  4.94171336,
        5.17947468,  5.42867544,  5.68986603,  5.96362332,  6.25055193,
        6.55128557,  6.86648845,  7.19685673,  7.54312006,  7.90604321,
        8.28642773,  8.68511374,  9.10298178,  9.54095476, 10.        ])},
             verbose=3)

In [10]:
#grid.fit(X_train_scaled, encoded_y)
#classifier.get_params().keys()
#grid.fit(X_train_scaled, encoded_y)
best_model = grid.fit(X_train_scaled, encoded_y)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV] C=1.0 ...........................................................
[CV] ............................... C=1.0, score=0.989, total=   0.1s
[CV] C=1.0 ...........................................................
[CV] ............................... C=1.0, score=0.994, total=   0.0s
[CV] C=1.0 ...........................................................
[CV] ............................... C=1.0, score=0.991, total=   0.0s
[CV] C=1.0 ...........................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV] ............................... C=1.0, score=0.993, total=   0.1s
[CV] C=1.0 ...........................................................
[CV] ............................... C=1.0, score=0.986, total=   0.0s
[CV] C=1.0481131341546857 ............................................
[CV] ................ C=1.0481131341546857, score=0.989, total=   0.0s
[CV] C=1.0481131341546857 ............................................
[CV] ................ C=1.0481131341546857, score=0.994, total=   0.0s
[CV] C=1.0481131341546857 ............................................
[CV] ................ C=1.0481131341546857, score=0.991, total=   0.0s
[CV] C=1.0481131341546857 ............................................
[CV] ................ C=1.0481131341546857, score=0.993, total=   0.0s
[CV] C=1.0481131341546857 ............................................
[CV] ................ C=1.0481131341546857, score=0.986, total=   0.1s
[CV] C=1.0985411419875581 ............................................
[CV] .

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:   19.4s finished


In [11]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])
# print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
# print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Best Penalty: l2
Best C: 7.196856730011519


In [12]:
print(best_model.best_params_)
print(best_model.best_score_)

{'C': 7.196856730011519}
0.9907483089491723


In [13]:
predictions = best_model.predict(X_test_scaled)
print(predictions)

[1 0 1 ... 1 1 1]


In [18]:
predictions = best_model.predict(X_test_scaled)
pd.DataFrame({"Prediction": label_encoder.inverse_transform(predictions), "Actual": y_test})

Prediction          Actual
0     FALSE POSITIVE  FALSE POSITIVE
1          CONFIRMED       CONFIRMED
2     FALSE POSITIVE  FALSE POSITIVE
3     FALSE POSITIVE  FALSE POSITIVE
4          CONFIRMED       CONFIRMED
...              ...             ...
1653  FALSE POSITIVE  FALSE POSITIVE
1654       CONFIRMED       CONFIRMED
1655  FALSE POSITIVE  FALSE POSITIVE
1656  FALSE POSITIVE  FALSE POSITIVE
1657  FALSE POSITIVE  FALSE POSITIVE

[1658 rows x 2 columns]

In [25]:
from sklearn.metrics import classification_report
label_encoder.transform(y_test)
predictions
print(classification_report(label_encoder.transform(y_test), predictions))


              precision    recall  f1-score   support

           0       0.99      0.97      0.98       539
           1       0.99      1.00      0.99      1119

    accuracy                           0.99      1658
   macro avg       0.99      0.99      0.99      1658
weighted avg       0.99      0.99      0.99      1658

